const data = {
  last_update: "2022-03-29",
  total_province: 34,
  provinces: [
    {
      kota: "Jakarta",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Jawa Barat",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Jawa Tengah",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Jawa Timur",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Banten",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Yogyakarta",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Kalimantan Timur",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Bali",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Sumatera Utara",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Riau",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Sulawesi Selatan",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Sumatera Barat",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Nusa Tenggara Timur",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Kalimantan Selatan",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Sumatera Selatan",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Lampung",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Kepulauan Riau",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Bangka Belitung",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Kalimantan Barat",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Sulawesi Tengah",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Kalimantan Tengah",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Sulawesi Utara",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Papua",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Kalimantan Utara",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Aceh",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Jambi",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Nusa Tenggara Barat",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Papua Barat",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Bengkulu",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Sulawesi Tenggara",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Maluku",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Sulawesi Barat",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Maluku Utara",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
    {
      kota: "Gorontalo",
      positif: 0,
      sembuh: 0,
      meninggal: 0,
      dirawat: 0,
    },
  ],
};

export default data;
